version: "3.8"

services:
  app:
    image: asistencia-app-back
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/venv
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      FLASK_ENV: development
    command: flask run --host=0.0.0.0 --port=5000
