version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: flask_container
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./flask:/app
      - /dev/dri:/dev/dri  # A침adir acceso a los gr치ficos integrados
      - /dev/video0:/dev/video0  # Montar primera c치mara
      - /dev/video1:/dev/video1  # Montar segunda c치mara (mismo dispositivo)
    working_dir: /app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    command: flask run --host=0.0.0.0
    networks:
      - yolo-deepface-network
    depends_on:
      - oracle-db

  oracle-db:
    image: container-registry.oracle.com/database/enterprise:21.3.0.0
    container_name: oracle-db
    restart: unless-stopped
    environment:
      - ORACLE_SID=attendance
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=OraclePassword123
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - yolo-deepface-network
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s espe_system/admin@//localhost:1521/ORCLPDB1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 1m

volumes:
  oracle-data:
    driver: local

networks:
  yolo-deepface-network:
    driver: bridge