version: '3.8'

services:
  yolo:
    build:
      context: .
      dockerfile: Dockerfile.yolo
    container_name: yolo_container
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./yolo:/usr/src/app
    working_dir: /usr/src/app
    command: sleep infinity
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    devices:
      - "/dev/video0:/dev/video0"
    networks:
      - yolo-deepface-network

  deepface:
    build:
      context: .
      dockerfile: Dockerfile.deepface
    container_name: deepface_container
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./deepface:/home/deepface
    working_dir: /home/deepface
    command: sleep infinity
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    devices:
      - "/dev/video0:/dev/video0"
    networks:
      - yolo-deepface-network

networks:
  yolo-deepface-network:
    driver: bridge
