# Dockerfile.deepface
FROM serengil/deepface:latest

# Instalar wget, nano y vi
RUN apt-get update && apt-get install -y \
    wget \
    nano \
    vim \
 && apt-get clean

# Establecer el directorio de trabajo
WORKDIR /home/deepface

# Usar la GPU (configuración ya presente en tu compose)
